/**
 * Triggered when the push token is generated by the device.
 */
export declare const PushToken = "push-token";
/**
 * Triggered when the user requests permission on the push event.
 */
export declare const PushPermissionRequest = "push-permission-request";
/**
 * Returns the state of the push request of the device.
 */
export declare const PushPermissionState = "push-permission-state";
type PushPermissionStateType = 'notDetermined' | 'denied' | 'authorized' | 'ephemeral' | 'provisional' | 'unknown' | 'granted';
interface WebKitMessageHandlers {
    [PushToken]: {
        postMessage: (message: string) => void;
    };
    [PushPermissionRequest]: {
        postMessage: (message: string) => void;
    };
    [PushPermissionState]: {
        postMessage: (message: string) => void;
    };
}
interface WebKit {
    messageHandlers: WebKitMessageHandlers;
}
declare global {
    interface Window {
        webkit?: WebKit;
    }
}
/**
 * Check if the client is a webview in an iOS or iPadOS device.
 */
export declare const usingAppleWebview: () => boolean;
export declare const requestPushPermissionState: () => void;
export declare const requestPushPermissions: () => void;
export declare const requestPushToken: () => void;
export interface PWABuilderHooks {
    hasFirebasePushState: (state: PushPermissionStateType) => boolean;
    registerFirebasePushNotificationListeners: () => void;
    removeFirebasePushNotificationListeners: () => void;
}
export declare const usePWABuilder: () => PWABuilderHooks;
export {};
